config/routes.rb
Rails.application.routes.draw do
  resources :tacos
  root to: 'tacos#index'
end

app/models/taco.rb
class Taco < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tacos_controller.rb
RANDOM_TACO_URL='http://api.giphy.com/v1/gifs/random?api_key=dc6zaTOxFJmzC&tag=taco'

class TacosController < ApplicationController
  before_action :set_taco, only: [:show, :edit, :update, :destroy]

  # GET /tacos
  # GET /tacos.json
  def index
    @tacos = Taco.all
  end

  # GET /tacos/1
  # GET /tacos/1.json
  def show
  end

  # GET /tacos/new
  def new
    @taco = Taco.new
  end

  # GET /tacos/1/edit
  def edit
  end

  # POST /tacos
  # POST /tacos.json
  def create
    response = RestClient.get RANDOM_TACO_URL
    random_taco = JSON.parse(response)['data']

    @taco = Taco.new(title: random_taco['caption'], url: random_taco['image_url'])
    @taco.save
    redirect_to action: 'index'

  end

  # PATCH/PUT /tacos/1
  # PATCH/PUT /tacos/1.json
  def update
    respond_to do |format|
      if @taco.update(taco_params)
        format.html { redirect_to @taco, notice: 'Taco was successfully updated.' }
        format.json { render :show, status: :ok, location: @taco }
      else
        format.html { render :edit }
        format.json { render json: @taco.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tacos/1
  # DELETE /tacos/1.json
  def destroy
    @taco.destroy
    respond_to do |format|
      format.html { redirect_to tacos_url, notice: 'Taco was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_taco
      @taco = Taco.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def taco_params
      params.require(:taco).permit(:title, :url)
    end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tacos_helper.rb
module TacosHelper
end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Tacolayer', root_path, class: 'navbar-brand'
      = link_to 'Automate a new taco', '/tacos', :method => :post, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Tacolayer'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Tacolayer'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/tacos/_form.html.haml
= form_for @taco do |f|
  - if @taco.errors.any?
    #error_explanation
      %h2= "#{pluralize(@taco.errors.count, "error")} prohibited this taco from being saved:"
      %ul
        - @taco.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :url
    = f.text_field :url
  .actions
    = f.submit 'Save'

app/views/tacos/edit.html.haml
%h1 Editing taco

= render 'form'

= link_to 'Show', @taco
\|
= link_to 'Back', tacos_path

app/views/tacos/index.html.haml
.container
  .row
    .col-lg-12
      %h4.page-header I am the taco and the taco is me ~ Tacolayer CEO
  - @tacos.each do |taco|
    .col-lg-3.col-md-4.col-xs-6.thumb
      %b= taco.title
      %a.thumbnail{:href => "#"}
        %img.img-responsive{:alt => "", :src => taco.url}
  %hr
    %footer
      .row
        .col-lg-12
          %p Copyright &copy; EAT MY TACO 2016

app/views/tacos/new.html.haml
%h1 New taco

= render 'form'

= link_to 'Back', tacos_path

app/views/tacos/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @taco.title
%p
  %b Url:
  = @taco.url

= link_to 'Edit', edit_taco_path(@taco)
\|
= link_to 'Back', tacos_path

app/views/visitors/index.html.haml
.container
  .row
    .col-lg-12
      %h1.page-header Taco Gallery
  - (1..16).each do |i|
    .col-lg-3.col-md-4.col-xs-6.thumb
      %b #{i}
      %a.thumbnail{:href => "#"}
        %img.img-responsive{:alt => "", :src => "http://placehold.it/400x300"}
  %hr
    %footer
      .row
        .col-lg-12
          %p Copyright &copy; EAT MY TACO 2016